### ISSUE TITLE
Change header background color

### ISSUE THREAD

**Issue by TheRealDannyyy** [ElectronForConstruct/greenworks-prebuilds-website#16]
#151515

![image](https://user-images.githubusercontent.com/15656049/63061701-59d6ea80-bef6-11e9-8984-37d52c5169c2.png)

**Comment by Armaldio** [comment]
Not sure #151515 is the best fit, for the GH icon for example

**Comment by TheRealDannyyy** [comment]
I'll change it to something fitting.

**Comment by TheRealDannyyy** [comment]
https://github.com/logos

Download and use the "mark" icon.
Resize and invert or wait until tomorrow for me to do it

**Comment by TheRealDannyyy** [comment]
This can be done now.
