### ISSUE TITLE
Prepare + publish website

### ISSUE THREAD

**Issue by TheRealDannyyy** [ElectronForConstruct/greenworks-prebuilds-website#17]
Forum post, promotion and general stuff that comes with it.

**Comment by Armaldio** [comment]
If you have nothing to do, make a project like in alfred, and put every issue inside
Will do post once project is done

**Comment by TheRealDannyyy** [comment]
There is no need for it. Once it's done, it would be fully automated anyway.

**Comment by TheRealDannyyy** [comment]
https://greenworks-prebuilds.armaldio.xyz/?runtime=nw.js&version=79,78&tag=v0.2.8

**Comment by TheRealDannyyy** [comment]
![image](https://user-images.githubusercontent.com/15656049/67641484-beed8a00-f902-11e9-9e06-6faf09ce3631.png)

**Comment by TheRealDannyyy** [comment]
Moved distribution stuff over here: https://github.com/ElectronForConstruct/greenworks-prebuilds-dist
