### ISSUE TITLE
GitHub login improvements

### ISSUE THREAD

**Issue by TheRealDannyyy** [ElectronForConstruct/greenworks-prebuilds-website#24]
- [x] Display guest icon (Download below)
- [x] Fetch user icon (GitHub)
- [x] Add CSS "border-radius: 3px;"
- [x] Add login/logout drop-down option on click
- [x] Display dialog box on error
- [x] Replace guest icon with user icon (no login success dialog box needed)

[githubguest.zip](https://github.com/ElectronForConstruct/greenworks-prebuilds-website/files/3739979/githubguest.zip)

**Comment by Armaldio** [comment]
If I add the user icon, I need to request one more scope when
authenticating, do you think it's OK?

Le jeu. 17 oct. 2019 à 17:03, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by TheRealDannyyy** [comment]
Yeah it's just one more read permission.
