### ISSUE TITLE
URL filtering broken

### ISSUE THREAD

**Issue by TheRealDannyyy** [ElectronForConstruct/greenworks-prebuilds-website#27]
Not sure if #11 is addressing this or something else, it's currently not possible to filter using an URL.

Example (NW.js, v77 only):
https://greenworks-prebuilds.armaldio.xyz/?runtime=nw.js&version=77

**Comment by Armaldio** [comment]
Is it ok if the url is not in sync with the selected elements ?

- Loading website with custom url: filter checkboxes
- Updating checkbox: nothing
- Hit share button: Generate shareable url

**Comment by TheRealDannyyy** [comment]
As long as I can link to an URL that automatically loads filters, it's fine for me.
