### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by clarknielsen** [ElectronForConstruct/greenworks-prebuilds-website#463]
Hi, I'm having trouble logging into the website. I'm redirected back to `/github-callback?code=<code>`, but the list of builds no longer loads because of the following error in the console:

```
SyntaxError: Unexpected token < in JSON at position 0
```

**Comment by Armaldio** [comment]
Tahnks a lot for the report.

I will fix that in the evening

**Comment by clarknielsen** [comment]
It works now! Thank you so much!
