### ISSUE TITLE
[Regression] Wrong prebuild names

### ISSUE THREAD

**Issue by TheRealDannyyy** [ElectronForConstruct/greenworks-prebuilds-website#47]
Expected:
![image](https://user-images.githubusercontent.com/15656049/67640798-e7728580-f8fc-11e9-8f59-a89d1cf38b33.png)

Current:
![image](https://user-images.githubusercontent.com/15656049/67640805-f3f6de00-f8fc-11e9-8fef-5ef4a4fe5eeb.png)

**Comment by Armaldio** [comment]
If you download 2 nw.js, x64, windows, how do you differentiate them?

**Comment by TheRealDannyyy** [comment]
By folder if possible else just append it before "greenworks". 

This has to be as simple and easy as possible. 
I bet there are people that won't even know what darwin is.
