### ISSUE TITLE
Share URL doesn't work with forum redirect

### ISSUE THREAD

**Issue by TheRealDannyyy** [ElectronForConstruct/greenworks-prebuilds-website#48]
The forum redirect is messing up special chars. Please replace any special chars if possible.

Original URL:
https://greenworks-prebuilds.armaldio.xyz?runtime=nw.js&version=79%2C78&tag=v0.2.8

Forum redirect URL:
https://www.construct.net/out?u=https%3a%2f%2fgreenworks-prebuilds.armaldio.xyz%2f%3fruntime%3dnw.js%26amp%3bversion%3d79%2c78%26amp%3btag%3dv0.2.8

**Comment by Armaldio** [comment]
It's not messing up, it's formatting characters to be url friendly

**Comment by Armaldio** [comment]
Oh, I get what you mean, it's parsing again while redirecting 🤔

**Comment by TheRealDannyyy** [comment]
If this has gone live. I can still reproduce it with the URL above.
Not fixed.

**Comment by Armaldio** [comment]
You need to regenerate the share url

**Comment by TheRealDannyyy** [comment]
Nope, still broken.

Expected: https://greenworks-prebuilds.armaldio.xyz?os=win32&arch=x64&runtime=nw.js&version=79,78&tag=v0.2.8

Forum redirect: https://www.construct.net/out?u=https%3a%2f%2fgreenworks-prebuilds.armaldio.xyz%2f%3fruntime%3dnw.js%26amp%3bversion%3d79%2c78%26amp%3btag%3dv0.2.8

**Comment by TheRealDannyyy** [comment]
Try removing the "&" char. I think that fails to parse on the forum.

**Comment by Armaldio** [comment]
I can't remove `&` since it's used natively to parse the URL query
I'll try on my own this evening but it seems to me that the redirect is not working is expected

**Comment by TheRealDannyyy** [comment]
I know that it's on their end but we should still try to find a workaround. The only way to avoid this right now would be to create a shortened link by a 3rd party.

I already reported it but you know, they're busy:
https://github.com/Scirra/Construct.net-website-bugs/issues/91

**Comment by Armaldio** [comment]
Ah, didn't knew it was confirmed on their side
I'll try to generate short url instead

**Comment by Armaldio** [comment]
Where can I try the behavior ?
Forum doesn't have a preview feature anymore

**Comment by TheRealDannyyy** [comment]
Temporally replace an existing post, that's how I've been doing it.

**Comment by Armaldio** [comment]
I've introduced short URLs, no complex characters so it's working fine with scirra's out feature and it's reducing drastically the length of the URL
