### ISSUE TITLE
Question regarding release tags

### ISSUE THREAD

**Issue by TheRealDannyyy** [ElectronForConstruct/greenworks-prebuilds-website#54]
Are they really necesarry? Don't we want users to always use the latest version anyway?

If they are a must-have, could you try any other form like a dropdown instead? I have a feeling that this section will get bloated really fast.

**Comment by Armaldio** [comment]
They are necessary in case a new release break the builds and get them corrupted
The user can just go back to an old release 

Of course we can restrict the website to only display the last one one, and if he want older releases, he must go to the github page

**Comment by TheRealDannyyy** [comment]
I guess changing to a dropdown would be better than elsd that section will take over the entire side bar in the future.
