### ISSUE TITLE
Can't Re-Generate Short URL bug

### ISSUE THREAD

**Issue by TheRealDannyyy** [ElectronForConstruct/greenworks-prebuilds-website#55]
1. https://greenworks-prebuilds.armaldio.xyz/
2. Generate short URL
3. Change properties on the left side
4. Notice you can't re-generate new URL

---
I'd honestly remove the old URL generation and always generate a new short URL when clicking on the generate URL button. Up to you to decide what to do.

**Comment by Armaldio** [comment]
Tell me a way to prevent abusive generation
I have *large* but still restrictive monthly limits

**Comment by TheRealDannyyy** [comment]
If you have to pay for it, you should consider using a 3rd party service like bitly.
I have no clue, either way people could abuse it.

**Comment by Armaldio** [comment]
Can't find a completely free service
Bitly have 500 links generations per month 

Currently, I'm using Firebase, once I reach the limit, the short url generation will simply stop working 

Here are the limits:
![Screenshot_20191104-080915](https://user-images.githubusercontent.com/3089715/68104211-8a696780-feda-11e9-803e-fe226fac3de0.jpg)
In order: reads, updates, deletes 
I think we're large enough until someday it become visited a lot
