### ISSUE TITLE
New versions of nw.js?

### ISSUE THREAD

**Issue by prominentdetail** [ElectronForConstruct/greenworks-prebuilds-website#697]
Any way to get new builds for the newest versions of nw.js?

**Comment by Armaldio** [comment]
Hello,

What do you mean by newest ?

![image](https://user-images.githubusercontent.com/3089715/196874133-d8342f81-50cf-4102-86a7-cd63d508a95f.png)

![image](https://user-images.githubusercontent.com/3089715/196874170-9e188eb0-c8c5-4ff6-81a5-771f32289704.png)

Latest versions are already supported

**Comment by Armaldio** [comment]
Oops, I'm just blind 0.62 < 0.69
My bad

I'll have a look

**Comment by Armaldio** [comment]
Fixed by https://github.com/ElectronForConstruct/greenworks-prebuilds/commit/feae1e38afa2f549896e0646cc1f930b503d1d86

**Comment by prominentdetail** [comment]
Thanks! :)

**Comment by prominentdetail** [comment]
@Armaldio Are any of the new nw.js versions going to get built as well? Seems like only the electron and node.js are getting updated. The nw.js version doesn't seem to get any new versions built.

**Comment by Armaldio** [comment]
The latest versions are not displayed correctly on the website
For version 69 you can use those

![Screenshot_20221030-093950.jpg](https://user-images.githubusercontent.com/3089715/198869894-3bd96493-5c0a-4a70-93dc-7cd688b4b5a0.jpg)

**Comment by prominentdetail** [comment]
Will the new version 70 be built as well and any other new versions?

**Comment by Armaldio** [comment]
Yes, they should build without changes on my part
I'm currently trying to fix the bug of my previous comment
