### ISSUE TITLE
Can't download any version

### ISSUE THREAD

**Issue by prominentdetail** [ElectronForConstruct/greenworks-prebuilds-website#744]
I'm trying to download on https://greenworks-prebuilds.armaldio.xyz/
But it just says preparing download, and never download it. I tried logging out and logging back in too.

I get these errors:
(removed)

**Comment by prominentdetail** [comment]
I guess I can download them here: https://github.com/ElectronForConstruct/greenworks-prebuilds/releases/tag/v0.7.0

**Comment by Armaldio** [comment]
I will have a look.

Can you give me more details about the files you are downloading and the browser you're using ?

Also, please note that you leaked your token in the screenshot
Reset your token by revoking access to the app: https://github.com/settings/applications?o=used-desc

**Comment by Armaldio** [comment]
After debugging, it seems that you tried to download an important number of files.
Try requesting less and let me know if it works.

**Comment by prominentdetail** [comment]
I tried again after revoking the app, then connecting the app again, and I was able to download the files.
Yesterday I only tried downloading two files, and I also tried just downloading one. Maybe the token was expired?
Anyways, now it works. Thanks.
