### ISSUE TITLE
Create a favicon

### ISSUE THREAD

**Issue by Armaldio** [ElectronForConstruct/greenworks-prebuilds-website#8]

**Comment by TheRealDannyyy** [comment]
I'm going to add a proper icon to the top-left and some link icons to the top-right later.
I can scale the main icon down and use it as a favicon.

**Comment by TheRealDannyyy** [comment]
I created an issue to keep track of this #10

**Comment by TheRealDannyyy** [comment]
If you need it in .ico format, use this: https://www.icoconverter.com/
